CREATE  TABLE users (
id  VARCHAR (MAX)  PRIMARY KEY NOT NULL UNIQUE,
fullname VARCHAR (MAX) NOT NULL ,
email VARCHAR(MAX) NOT NULL UNIQUE,
password VARCHAR (MAX) NOT NULL UNIQUE,
role VARCHAR(MAX) NOT NULL DEFAULT 'users',
dateRegistered DATETIME DEFAULT GETDATE()
)